#!/bin/sh
set -eu

parallel=${TEST_PARALLEL:-8}
: "${GOCACHE:=${TMPDIR:-/tmp}/sqlite-go-cache}"
export GOCACHE
export SQLITE_TEST_STORAGE_ENGINE=minweight

# Coverage notes:
# See MINWEIGHT_STORAGE_ENGINE.md for progress, TODOs, and slow-test policy.
# - sqlite_dbpage and custom-VFS snapshot compatibility are lower-priority shim checks.
#   They run in broad/full minweight tests, not in this focused semantic list.
# - Native sqlite3_serialize/sqlite3_deserialize expose SQLite page images; minweight uses a logical snapshot for round-trip behavior.
minweight_tests='^(TestMinweightStorageEngineSimpleSPJ|TestMinweightStorageEngineUniqueTextLookup|TestMinweightStorageEngineIntegrityCheck|TestMinweightStorageEngineQueryRowMultiStatement|TestMinweightStorageEngineVarcharPrimaryKey|TestMinweightStorageEngineAttachCommitRollback|TestMinweightStorageEngineWithoutRowidCompositePrimaryKey|TestMinweightStorageEngineUncommittedWriteInvisibleToOtherConnection|TestMinweightStorageEngineRejectsConcurrentWriters|TestMinweightStorageEngineBusyTimeoutWaitsForWriter|TestMinweightStorageEngineOpenReadCursorUsesPinnedViewAfterWriterCommit|TestMinweightStorageEngineExplicitReadTransactionBlocksWriterCommit|TestMinweightStorageEngineJournalModeWALStaysRollback|TestMinweightStorageEngineTableCursorSeekSkipsRowidGapsAndOverlay|TestMinweightStorageEngineIssue19Shape|TestMinweightStorageEngineOrderByPreservesColumns|TestMinweightStorageEngineBuiltinWindowSum|TestMinweightStorageEngineLogicalSerializeRoundTrip|TestMinweightStorageEngineLogicalSerializePreservesSQLiteSequence|TestMinweightStorageEngineLogicalBackupPreservesSQLiteSequence|TestMinweightStorageEngineLogicalSerializePreservesGeneratedColumns|TestMinweightStorageEngineLogicalBackupPreservesGeneratedColumns|TestMinweightStorageEngineLogicalBackupPreservesHiddenRowid|TestMinweightStorageEngineLogicalSerializePreservesFTS5VirtualTable|TestMinweightStorageEngineLogicalBackupPreservesFTS5VirtualTable|TestMinweightStorageEngineUpsertReplaceMaintainsIndexes|TestMinweightStorageEngineForeignKeyCascadeAndTriggers|TestMinweightStorageEnginePartialExpressionIndexWrites|TestMinweightStorageEngineFailedStatementRollsBackTriggerWrites|TestMinweightStorageEngineDeferredForeignKeyCommitFailureDoesNotPublish|TestMinweightStorageEngineVacuumTransfersRows|TestMinweightStorageEngineDropTableMovesAutoVacuumRoot|TestMinweightStorageEngineDropTableReusesFreedRoot|TestMinweightStorageEngineBtreePragmaState|TestMinweightStorageEnginePathBackedStorePersistsAcrossEngine|TestMinweightStorageEnginePathBackedRollbackDoesNotPersistOverlay|TestMinweightStorageEngineReadOnlyPathOpenFailsFast|TestMinweightStorageEngineLogicalSerializePreservesBtreePragmaState|TestMinweightStorageEngineLogicalSerializePreservesReusedTableRoot|TestMinweightStorageEngineLogicalSerializePreservesIndexRootBelowTable|TestMinweightStorageEngineLogicalBackupRestorePreservesIndexRootBelowTable|TestMinweightStorageEngineLogicalRoundTripPreservesFreelistReuseOrder|TestMinweightStorageEngineTransactionRollbackRestoresRows|TestMinweightStorageEngineSavepointRollbackRestoresRows|TestMinweightStorageEngineStatementRollbackRestoresRows)$'
top_level_tests='^(TestIssue19|TestScalar|TestBlob|TestBinding|TestColumnTextScan|TestExecReturningMultiRow|TestExecReturningMultiStatement|TestMemDB|TestSingleConn|TestBeginMode|TestTxCommitBusyFix|TestConstraintPrimaryKeyError|TestConstraintUniqueError|TestConcurrentGoroutines|TestBackupProgress|TestPreUpdateHook|TestFcntlDataVersion|TestFcntlPersistWAL|TestVtabUpdaterInsertUpdateDelete)$'
dispatch_tests='^TestStorageEngineOpenConnectionsKeepBoundEngineAfterGlobalSwitch$'

echo 'run focused minweight adapter behavior tests'
go test -p "$parallel" -parallel "$parallel" -timeout 180s -run "$minweight_tests"

echo 'run focused top-level SQL behavior tests under minweight'
go test -p "$parallel" -parallel "$parallel" -timeout 180s -run "$top_level_tests"

echo 'run handle-bound dispatch switch test'
SQLITE_TEST_STORAGE_ENGINE= go test -p "$parallel" -parallel "$parallel" -timeout 180s -run "$dispatch_tests"

echo 'run focused minweight lib cursor tests'
go test -p "$parallel" -parallel "$parallel" -timeout 180s ./lib

echo 'run focused minweight serialize behavior tests'
go test -p "$parallel" -parallel "$parallel" -timeout 180s -run '^TestRegisteredFunctions/(serialize_and_deserialize|serialize_and_deserialize_allocator)$'
