#!/bin/sh
set -eu

parallel=${TEST_PARALLEL:-8}
: "${GOCACHE:=${TMPDIR:-/tmp}/sqlite-go-cache}"
export GOCACHE
export SQLITE_TEST_STORAGE_ENGINE=minweight

# Default per-turn gate. Keep this list high-signal and under about 30s.
# Broader scripts are intentionally reduced-frequency; see MINWEIGHT_STORAGE_ENGINE.md.
quick_tests='^(TestStorageEngineOpenConnectionsKeepBoundEngineAfterGlobalSwitch|TestMinweightStorageEngineSimpleSPJ|TestMinweightStorageEngineWithoutRowidCompositePrimaryKey|TestMinweightStorageEnginePathBackedStorePersistsAcrossEngine|TestMinweightStorageEnginePathBackedRollbackDoesNotPersistOverlay|TestMinweightStorageEngineOpenReadCursorUsesPinnedViewAfterWriterCommit|TestMinweightStorageEngineJournalModeWALStaysRollback|TestMinweightStorageEngineTransactionRollbackRestoresRows|TestMinweightStorageEngineSavepointRollbackRestoresRows|TestMinweightStorageEngineStatementRollbackRestoresRows|TestMinweightComparableMemKeyIgnoresNegativeLengthForInteger|TestMinweightIndexMovetoUsesVersionedSeek|TestMinweightBtreeCommitReturnsBusySnapshotOnReadConflict|TestMinweightCommitDetectsReadSetConflict|TestMinweightCommitDetectsRangeReadConflict|TestMinweightPinnedReaderPointGetUsesOldGeneration|TestMinweightPinnedReaderTableSeekUsesOldGeneration|TestMinweightPinnedReaderIndexSeekUsesOldGeneration|TestMinweightPinnedReaderMetadataUsesOldGeneration|TestMinweightIndexNextWithoutVersionedStoreKeyFailsFast|TestMinweightStatsRejectLegacyRawIndexKey|TestMinweightBtreeCopyFileUsesSourceOverlayAndTargetTxn)$'

go test -p "$parallel" -parallel "$parallel" -timeout 30s -run "$quick_tests" ./ ./lib
